### ISSUE TITLE
Getting an Exception while generating model documentation

### ISSUE THREAD

**Issue by gbuisson** [threatgrid/flanders#18]
```
Writing structures/bundle.md...Exception in thread "main" java.lang.IllegalArgumentException: No implementation of method: :->short-description of protocol: #'flanders.markdown/MarkdownNode found for class: clojure.core$type, compiling:(/private/var/folders/bk/l3fs1db15d7f0gqk_70465k40000gn/T/form-init3207164969018235252.clj:1:125)
	at clojure.lang.Compiler.load(Compiler.java:7526)
	at clojure.lang.Compiler.loadFile(Compiler.java:7452)
	at clojure.main$load_script.invokeStatic(main.clj:278)
	at clojure.main$init_opt.invokeStatic(main.clj:280)
```

**Comment by hshahman** [comment]
No QA required.
